version: "3.8"

services:
  my-deno-website-dev:
    image: robertfent1/deno-website:dev
    container_name: my-deno-website-dev
    ports:
      - 8071:8071
    environment:
      - MODE=0
    labels:
      - "traefik.http.routers.deno-dev.rule=Host(`dev-website.robertfent.dev`)"
      - "traefik.http.routers.deno-dev.tls=true"
      - "traefik.http.routers.deno-dev.tls.certresolver=lets-encrypt"
      - "traefik.port=8071"
    networks:
      - db
      - web

networks:
  db:
    external: true
  web:
    external: true