version: "3.8"

services:
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config
    labels:
      - "traefik.enable=false"
    environment: 
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_POLL_INTERVAL=30
    networks:
      - web
  
networks:
  web:
    external: true